openapi: 3.0.2
info:
  version: 1.0.0
  title: MysteryDrop.app
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: >
    This documentation describes how the web client should interact with the Mystery Drop serverless back end.

    # Introduction

    The Mystery Drop API is available in the dev environment.

tags:
  - name: Hello Auth
    description: Example authenticated endpoint intended for testing session JWTs
  - name: Sessions
    description: Authentication endpoints
servers:
  - url: 'https://dev.ext-api.mysterydrop.app/app/v1'
  - url: 'https://prod.ext-api.mysterydrop.app/app/v1'
paths:
  /sessions:
    $ref: paths/sessions.yaml
  /helloAuth:
    $ref: paths/helloAuth.yaml
components:
  securitySchemes:
    bearer_auth:
      $ref: 'components/securitySchemes/bearer_auth.yaml'
